language: python
python:
    - 3.6
install:
    - pip install pipenv
    - pipenv install --dev
script:
    - ./manage.py migrate
    - coverage run manage.py test
    - flake8 .
after_success:
    - coveralls
